from web_harness import *
from suite_axe import scan as _scan

def scan(pg, name):
    _scan(pg, name)
    small = small_targets(pg)
    check(f'targets 44px: {name}', not small)
    if small: print(f'--- small targets: {name} ---\n' + '\n'.join(small))
    labels = off_scale_labels(pg)
    check(f'label text 16px: {name}', not labels)
    if labels: print(f'--- off-scale labels: {name} ---\n' + '\n'.join(labels))
    off = off_scale_buttons(pg)
    check(f'button text 16px: {name}', not off)
    if off: print(f'--- off-scale buttons: {name} ---\n' + '\n'.join(off))

def run(b):
    for scheme in ('light', 'dark'):
        c = new_ctx(b, scheme); pg = open_app(c, onboarded=False)
        scan(pg, f'web {scheme} sign in')
        pg.fill('#l-email', ACC['a']); pg.fill('#l-pass', 'wrong'); pg.click('#l-btn'); pg.wait_for_timeout(150)
        scan(pg, f'web {scheme} sign in error')
        login_to(pg, 'a', '#onboarding'); scan(pg, f'web {scheme} onboarding privacy')
        pg.click('#onboarding summary'); scan(pg, f'web {scheme} onboarding full details')
        pg.click('[data-act=ob-continue]'); pg.click('[data-act=pw-save]'); pg.wait_for_timeout(50); scan(pg, f'web {scheme} onboarding password error')
        pg.click('[data-act=pw-skip]'); pg.wait_for_selector('.hero'); pg.wait_for_timeout(150)
        scan(pg, f'web {scheme} home empty')
        fs_write(pg, 'expenses/k1', {'amountCents': 120000, 'payer': 'p2', 'merchant': 'Costco', 'category': 'Groceries', 'date': '2026-08-01',
                                      'split': 'full', 'settled': False, 'createdBy': 'p2', 'createdAt': 1})
        scan(pg, f'web {scheme} home with reminder and rows')
        for name in ('history', 'insights', 'settings'): tab(pg, name); scan(pg, f'web {scheme} {name}')
        pg.click('[data-act=privacy]'); pg.wait_for_timeout(100); scan(pg, f'web {scheme} privacy page')
        c.close()
        c = new_ctx(b, scheme); pg = open_app(c); login(pg)
        start_add(pg); scan(pg, f'web {scheme} add amount')
        next_step(pg); scan(pg, f'web {scheme} add amount error')
        pg.click('[data-act=pick-bill]'); pg.wait_for_selector('#bills'); pg.wait_for_timeout(150); scan(pg, f'web {scheme} bills drawer')
        pg.click('#bills [data-act=bill][data-id=water]'); pg.wait_for_timeout(250); scan(pg, f'web {scheme} add bill picked')
        next_step(pg); pg.wait_for_timeout(200); scan(pg, f'web {scheme} review a bill')
        pg.click('[data-act=back]'); pg.wait_for_timeout(80); pg.click('[data-act=clear-bill]'); keys(pg, '45.12'); next_step(pg); scan(pg, f'web {scheme} add store')
        next_step(pg); pg.wait_for_timeout(50); scan(pg, f'web {scheme} add store error')
        pg.check('input[name=store][value=costco]'); scan(pg, f'web {scheme} add store selected')
        open_details(pg); scan(pg, f'web {scheme} details drawer'); details_done(pg)
        pg.fill('#w-q', 'Blue Bottle'); pg.check('input[name=store][value=__new__]'); next_step(pg); pg.wait_for_timeout(50)
        scan(pg, f'web {scheme} add new-store error')
        pg.select_option('#w-cat', 'Coffee'); next_step(pg); pg.wait_for_timeout(150); scan(pg, f'web {scheme} review')
        log_it(pg); pg.wait_for_timeout(100); scan(pg, f'web {scheme} home with the saved toast')
        start_add(pg); keys(pg, '45.12'); next_step(pg); pg.fill('#w-q', 'blue'); pg.check('input[name=store][value=blue-bottle]'); next_step(pg); pg.wait_for_timeout(150)
        scan(pg, f'web {scheme} duplicate warning on review')
        close_sheet(pg)
        eid = [k for k in st(pg) if k.startswith('expenses/')][0].split('/')[1]
        pg.click(f'[data-act=edit][data-id="{eid}"]'); pg.wait_for_selector('#e-amt'); scan(pg, f'web {scheme} edit')
        pg.fill('#e-amt', ''); pg.click('[data-act=e-save]'); pg.click('[data-act=e-delete]'); pg.wait_for_timeout(50)
        scan(pg, f'web {scheme} edit error, delete armed')
        close_sheet(pg)
        fs_batch(pg, [('settlements/s1', {'date': '2026-09-30', 'createdAt': 2, 'from': 'p1', 'to': 'p2', 'amountCents': 37744, 'count': 1,
                                          'p1Half': 4512, 'p2Half': 0, 'p1Full': 0, 'p2Full': 40000}),
                      ('expenses/d1', {'amountCents': 4512, 'payer': 'p1', 'merchant': 'Costco', 'category': 'Groceries', 'date': '2026-09-29',
                                       'split': 'half', 'settled': True, 'settlementId': 's1', 'createdBy': 'p1', 'createdAt': 5})])
        tab(pg, 'history'); scan(pg, f'web {scheme} history settle-ups')
        pg.click('[data-act=detail][data-id=s1]'); pg.wait_for_timeout(250); scan(pg, f'web {scheme} settle-up details')
        close_sheet(pg)
        pg.click('[data-act=h-activity]'); pg.wait_for_timeout(200); scan(pg, f'web {scheme} activity')
        c.close()
        c = new_ctx(b, scheme); pg = open_app(c); login(pg)
        fs_batch(pg, [exp_row('e1', 4512, 'p1', 'half', ago(5)), exp_row('e2', 40000, 'p2', 'full', ago(4))]); fs_write(pg, 'config/profile-p2', {'venmo': 'sam-test'})
        scan(pg, f'web {scheme} home with Settle up')
        open_settle(pg); scan(pg, f'web {scheme} settle up, you owe')
        pg.click('[data-act=how]'); scan(pg, f'web {scheme} settle up, breakdown open')
        pg.click('[data-act=settle-other]'); pg.wait_for_selector('#settle-confirm'); pg.wait_for_timeout(200); scan(pg, f'web {scheme} settle confirm drawer')
        pg.click('[data-act=settle-no]'); pg.wait_for_timeout(200)
        pg.evaluate("document.querySelector('a[data-act=venmo]').addEventListener('click', e => e.preventDefault())"); pg.click('a[data-act=venmo]')
        pg.evaluate("document.dispatchEvent(new Event('visibilitychange'))"); pg.wait_for_timeout(300); scan(pg, f'web {scheme} venmo question')
        fs_batch(pg, [exp_row('e3', 600, 'p2')]); pg.wait_for_timeout(250); scan(pg, f'web {scheme} venmo question withdrawn')
        fs_write(pg, 'config/profile-p2', {'venmo': None}); pg.wait_for_timeout(150); scan(pg, f'web {scheme} settle up, no username')
        close_sheet(pg)
        fs_batch(pg, [exp_row('e5', 1000, 'p2', 'half', ago(70))]); pg.wait_for_timeout(150); scan(pg, f'web {scheme} home with the reminder')
        c.close()
        c = new_ctx(b, scheme); pg = open_app(c); login(pg)
        tab(pg, 'settings'); scan(pg, f'web {scheme} settings tab')
        pg.click('[data-act=profile]'); pg.wait_for_timeout(200); scan(pg, f'web {scheme} profile')
        pg.fill('#p-emoji', 'ab'); pg.click('[data-act=emoji-save]'); pg.fill('#p-venmo', 'ab'); pg.click('[data-act=venmo-save]'); pg.wait_for_timeout(100)
        scan(pg, f'web {scheme} profile with errors')
        fs_write(pg, 'config/profile-p2', {'color': 'violet', 'updatedAt': 1}); fs_write(pg, 'config/profile-p1', {'updatedAt': 9_999_999_999_999})
        scan(pg, f'web {scheme} profile, colors clash')
        pg.click('[data-act=change-pw]'); pg.wait_for_selector('#pw-new'); pg.wait_for_timeout(250); scan(pg, f'web {scheme} change password')
        close_sheet(pg); pg.click('[data-act=back-settings]'); pg.wait_for_timeout(150)
        pg.click('[data-act=reminder]'); pg.wait_for_timeout(150); scan(pg, f'web {scheme} reminder')
        pg.click('[data-act=back-settings]'); pg.wait_for_timeout(150)
        pg.click('[data-act=stores]'); pg.wait_for_timeout(150); scan(pg, f'web {scheme} stores')
        pg.click('[data-act=store-open][data-id=aldi]'); pg.wait_for_selector('#sd-name'); pg.wait_for_timeout(150); scan(pg, f'web {scheme} a store')
        pg.fill('#sd-name', ''); pg.click('[data-act=store-rename]'); pg.wait_for_timeout(80); scan(pg, f'web {scheme} a store, name error')
        pg.fill('#sd-name', 'costco'); pg.click('[data-act=store-rename]'); pg.wait_for_timeout(120); scan(pg, f'web {scheme} a store, merge offer')
        pg.fill('#sd-name', 'Aldi')
        pg.click('[data-act=store-merge-open]'); pg.wait_for_function("document.getElementById('merge')?.contains(document.activeElement)"); pg.wait_for_timeout(250)
        pg.click('[data-act=store-merge]'); pg.wait_for_timeout(80); scan(pg, f'web {scheme} merge drawer, with error')
        pg.click('[data-act=merge-cancel]'); pg.wait_for_timeout(250)
        pg.click('[data-act=store-remove]'); pg.wait_for_function("document.getElementById('remove')?.contains(document.activeElement)"); pg.wait_for_timeout(250)
        scan(pg, f'web {scheme} remove drawer'); pg.click('[data-act=store-remove-yes]'); pg.wait_for_timeout(250)
        scan(pg, f'web {scheme} stores with Removed')
        pg.click('[data-act=back-settings]'); pg.wait_for_timeout(150); pg.click('[data-act=bills]'); pg.wait_for_timeout(150); scan(pg, f'web {scheme} bills')
        pg.click('[data-act=bill-new]'); pg.wait_for_selector('#bf-name'); pg.wait_for_timeout(250); scan(pg, f'web {scheme} add bill')
        pg.click('[data-act=bill-save]'); pg.wait_for_timeout(80); scan(pg, f'web {scheme} add bill, error')
        close_sheet(pg); pg.click('[data-act=bill-open][data-id=water]'); pg.wait_for_selector('#bf-name'); pg.wait_for_timeout(250); scan(pg, f'web {scheme} edit bill')
        pg.click('[data-act=bill-retire]'); pg.wait_for_function("document.getElementById('retire')?.contains(document.activeElement)"); pg.wait_for_timeout(250)
        scan(pg, f'web {scheme} retire drawer')
        pg.click('[data-act=retire-cancel]'); pg.wait_for_timeout(250); close_sheet(pg)
        c.close()
        c = new_ctx(b, scheme); c.add_init_script("window.__today = '2026-08-20'"); pg = open_app(c); login(pg)
        fs_write(pg, 'config/history', {'through': '2026-07', 'months': {m: {'cats': {'Groceries': 60000, 'Dining & takeout': 30000}, 'bills': {'electricity': 64555},
                 'oneOffs': {}, 'oneOffCount': 0} for m in ('2026-02', '2026-03', '2026-04', '2026-05', '2026-06', '2026-07')}})
        fs_batch(pg, [exp_row('i1', 90000, 'p1', 'half', '2026-08-05'), ('expenses/i4', dict(exp_row('i4', 150849, 'p1', 'half', '2026-08-12')[1], oneOff=True))])
        tab(pg, 'insights'); pg.wait_for_selector('#ontrack'); pg.wait_for_timeout(150); scan(pg, f'web {scheme} insights, running high')
        pg.click('#usual-how summary'); scan(pg, f'web {scheme} insights, usual explained')
        pg.click('[data-act=needs-open]'); pg.wait_for_selector('#needs-table'); pg.wait_for_timeout(250); scan(pg, f'web {scheme} needs sheet')
        close_sheet(pg); pg.click('[data-act=month-prev]'); pg.wait_for_timeout(200); scan(pg, f'web {scheme} insights, past month')
        pg.evaluate("location.hash = '#/insights/2026-01'"); pg.wait_for_timeout(200); scan(pg, f'web {scheme} insights, not enough history')
        tab(pg, 'settings'); pg.click('[data-act=buckets]'); pg.wait_for_timeout(200); scan(pg, f'web {scheme} needs and wants mapping')
        tab(pg, 'home'); start_add(pg); keys(pg, '9'); next_step(pg); pg.check('input[name=store][value=costco]'); open_details(pg)
        scan(pg, f'web {scheme} details with one-off'); details_done(pg); close_sheet(pg)
        c.close()
